export class DatosVets{
    _idVets="";
    _image="";
    _idUsuarioCreacion="";
    _tipoVet="";
    _nombreVet="";
    _lemaVet="";
    _descripcionVet="";
    _correoVet="";
    _direccionVet="";
    _paginaWebVet="";
    _celularVet="";
    _telefonoVet="";
    _horarioVet="";
    _diasAtencionVet="";
    _serviciosVet="";
    _fecha_creacionVet="";
    _fecha_modificacionVet="";
    _coordenadasVets="";
    _facebookVets="";
    _twitterVets="";
    _InstagramVets="";
    _whatSappVets="";
    _24Horas="";
}